import 'package:spotify_clone/models/song.dart';

final likedSongs = [
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'Lover',
    artistName: 'Taylor Swift',
    tags: ['Lyrics'],
    liked: true,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'I Think He Knows',
    artistName: 'Taylor Swift',
    tags: ['Lyrics'],
    liked: true,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'Paper Rings',
    artistName: 'Taylor Swift',
    tags: ['Lyrics'],
    liked: true,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'You Need To Calm Down',
    artistName: 'Taylor Swift',
    tags: ['Lyrics'],
    liked: true,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'ME! (feat. Brendon Urie of Panic! At The Disco)',
    artistName: 'Taylor Swift, Brendon Urie, Panic! At The Disco',
    tags: ['Lyrics'],
    liked: true,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'London Boy',
    artistName: 'Taylor Swift',
    tags: [],
    liked: false,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'London Boy',
    artistName: 'Taylor Swift',
    tags: [],
    liked: false,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'London Boy',
    artistName: 'Taylor Swift',
    tags: [],
    liked: false,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'London Boy',
    artistName: 'Taylor Swift',
    tags: [],
    liked: false,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'London Boy',
    artistName: 'Taylor Swift',
    tags: [],
    liked: false,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'London Boy',
    artistName: 'Taylor Swift',
    tags: [],
    liked: false,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'London Boy',
    artistName: 'Taylor Swift',
    tags: [],
    liked: false,
  ),
];
