import 'package:spotify_clone/models/song.dart';

final likedSongs = [
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'Lover',
    artistName: 'Taylor Swift',
    tags: ['Lyrics'],
    mp3Path: 'songs/Taylor_Swift_Lover.mp3',
    liked: true,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'I Think He Knows',
    artistName: 'Taylor Swift',
    tags: ['Lyrics'],
    mp3Path: 'songs/i_think_he_knows.mp3',
    liked: true,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'Paper Rings',
    artistName: 'Taylor Swift',
    tags: ['Lyrics'],
    mp3Path: 'songs/paper_rings.mp3',
    liked: true,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'You Need To Calm Down',
    artistName: 'Taylor Swift',
    tags: ['Lyrics'],
    mp3Path: 'songs/you_need_to_calm_down.mp3',
    liked: true,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'ME! (feat. Brendon Urie of Panic! At The Disco)',
    artistName: 'Taylor Swift, Brendon Urie, Panic! At The Disco',
    tags: ['Lyrics'],
    mp3Path: 'songs/me.mp3',
    liked: true,
  ),
  Song(
    coverImage: 'assets/images/lover.jpeg',
    title: 'London Boy',
    artistName: 'Taylor Swift',
    tags: [],
    mp3Path: 'songs/london_boy.mp3',
    liked: false,
  ),
  Song(
    coverImage: 'assets/images/speak_now.png',
    title: 'Mine',
    artistName: 'Taylor Swift',
    tags: ['Lyrics'],
    mp3Path: 'songs/mine.mp3',
    liked: false,
  ),
  Song(
    coverImage: 'assets/images/speak_now.png',
    title: 'Long Live',
    artistName: 'Taylor Swift',
    tags: ['Lyrics'],
    mp3Path: 'songs/long_live.mp3',
    liked: false,
  ),
  Song(
    coverImage: 'assets/images/monster.jpeg',
    title: '怪物',
    artistName: 'YOASOBI',
    tags: [],
    mp3Path: 'songs/monster.mp3',
    liked: true,
  ),
  // Song(
  //   coverImage: 'assets/images/red_taylors_version.png',
  //   title: 'Starlight (Taylor\'s Version)',
  //   artistName: 'Taylor Swift',
  //   tags: [],
  //   liked: false,
  // ),
  // Song(
  //   coverImage: 'assets/images/red_taylors_version.png',
  //   title: 'Message In A Bottle (Taylor\'s Version)',
  //   artistName: 'Taylor Swift',
  //   tags: [],
  //   liked: false,
  // ),
  Song(
    coverImage: 'assets/images/nine_track_mind.png',
    title: 'Marvin Gaye (feat. Meghan Trainor)',
    artistName: 'Charlie Puth, Meghan Trainor',
    tags: ['Lyrics', 'E'],
    mp3Path: 'songs/marvin_gaye.mp3',
    liked: false,
  ),
];
